version: '3.1'
services:
  db:
    image: postgres:12.5
    env_file:
      - .env.pg
    ports:
      - "5436:5432"
    volumes:
      - ./storage:/tmp/backup
      - corus_genero_db:/var/lib/postgresql/data

  ruby:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3100:3000"
    env_file:
      - .env.ruby
    command: ./unicorn.sh
    stdin_open: true
    tty: true
    volumes:
     - .:/app
     - corus_genero_tmp_cache:/tmp
    depends_on:
      - db

volumes:
  corus_genero_db:
  corus_genero_tmp_cache: