version: '2'
services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./storage:/tmp/backup
      - kar_genero:/var/lib/postgresql/data

  ruby:
    image: kar:ruby2.4.0-ga
    command: ./unicorn.sh
    volumes:
     - .:/app
     - genero_tmp_cache:/tmp
     - genero_unicorn:/unicorn
    depends_on:
      - db

  web:
    image: nginx:latest
    ports:
      - "8092:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - ruby
    depends_on:
      - db
      - ruby
    links:
      - ruby

volumes:
  kar_genero:
  genero_tmp_cache:
  genero_unicorn: