version: '3.1'
services:
  db:
    image: postgres:12.5
    env_file:
      - .env.pg
    ports:
      - "5436:5432"
    volumes:
      - ./storage:/tmp/backup
      - corus_genero_db:/var/lib/postgresql/data

  ruby:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3100:3000"
    env_file:
      - .env.ruby
    command: ./unicorn.sh
    volumes:
     - .:/app
     - corus_genero_tmp_cache:/tmp
    depends_on:
      - db

#  web:
#    image: nginx:latest
#    ports:
#      - "8092:80"
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    volumes_from:
#      - ruby
#    depends_on:
#      - db
#      - ruby
#    links:
#      - ruby

volumes:
  corus_genero_db:
  corus_genero_tmp_cache: